use_frameworks!

platform :ios, '12.4'

target 'RxNormKit_Example' do
  pod 'RxNormKit', :path => '../'
  pod 'RealmSwift', '~> 10.43'
  pod 'SwiftLint'

  target 'RxNormKit_Tests' do
    inherit! :search_paths

    
  end
end
